setup:
	go get github.com/99designs/gqlgen
	go get github.com/99designs/gqlgen/codegen
	curl -sSfL https://raw.githubusercontent.com/cosmtrek/air/master/install.sh | sh -s

run:
	./bin/air

gen:
	go run github.com/99designs/gqlgen generate
